title: Shutup and Code
markdown: kramdown
highlighter: rouge
safe: true
lsi: false
include: [".well-known"]
timezone: America/New_York
permalink: pretty
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

url: http://icepick.info
