# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
timezone: America/New_York
include: [".well-known"]
safe: true

# Permalinks
permalink: pretty

# Setup
title: 'Shutup and Code'
tagline: 'babblings of Myers Carpenter'
description: ''
url: http://icepick.info
baseurl: /

author:
  name: 'Myers Carpenter'
  url: https://github.com/myers

paginate: 5

plugins:
  - jekyll-feed
